name: example
build: ./
extends: ./env_extend.yml
services:
  - mongo:
      image: mongo:4.4
      restart: on-failure:3
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
      ports:
        - 27017:27017
      hostname: mongo-db
  - redis:
      extends: ./dvbx_redis_config.yml
      environment:
        - TEST=foo
      hostname: redis-server
workdir: /app
environment:
  - HOST_USER=${USER}
ports:
  - 1234:1234
privileged: true
before: echo 'Before script'
after: echo 'After script'
tasks:
  test: |
    echo 'Hello, world!'
    echo 'Hello, kent!'
  env: env | sort
  fail: exit 100
  shell: /bin/bash
  greet: echo 'Hello {{name}}'
